export interface DesignMood {
  name: string;
  colorPalette: string;
  typography: string;
  layoutStyle: string;
  density: 'sparse' | 'balanced' | 'dense';
  mood: string;
  cssApproach: string;
  heroPattern: string;
  sectionVariations: string[];
  signatureElements: string[];
  typographicScale: string;
  colorUsageRules: string;
}

export const DESIGN_MOODS: DesignMood[] = [
  {
    name: 'brutalist-editorial',
    colorPalette: 'Stark black (#000), white (#fff), and a single aggressive red (#ff2200). No gradients.',
    typography: 'Massive bold sans-serif headlines (Space Grotesk or Archivo Black at 6-8rem). Small monospace body text. Extreme contrast between heading and body sizes.',
    layoutStyle: 'Broken grids, overlapping elements, asymmetric columns, visible borders, raw structure.',
    density: 'balanced',
    mood: 'Bold, confrontational, art-school editorial. Anti-corporate, statement-making.',
    cssApproach: 'Custom CSS for asymmetric grids and overlapping transforms. Minimal Tailwind.',
    heroPattern: 'Full-viewport split: one side is a massive single word in 10rem type, the other side is a stark image or solid color block. No padding.',
    sectionVariations: ['Offset two-column with text bleeding into image', 'Horizontal scroll marquee with oversized type', 'Stacked full-width text blocks with alternating black/white backgrounds', 'Raw grid with misaligned cards and visible grid lines'],
    signatureElements: ['Thick black borders on everything', 'Text rotated -90deg as labels', 'Oversized cursor-following elements', 'Mix of serif and mono in unexpected places'],
    typographicScale: 'Display: 8rem, H1: 4rem, H2: 2rem, Body: 0.875rem mono, Caption: 0.7rem',
    colorUsageRules: 'Black and white are the only background colors. Red is used exclusively for one accent element per section (a line, a word, a dot). Never use red for backgrounds.',
  },
  {
    name: 'warm-organic',
    colorPalette: 'Terracotta (#c2703e), sage green (#8a9a5b), warm cream (#f5f0e8), soft brown (#6b4f3a), muted gold (#c9a959).',
    typography: 'Elegant serif for headings (DM Serif Display or Playfair Display). Clean sans-serif body (Nunito or Lato). Generous line-height 1.8.',
    layoutStyle: 'Rounded corners (16-24px), organic flowing sections, soft shadows, natural imagery.',
    density: 'sparse',
    mood: 'Handcrafted, artisanal, earthy warmth. Feels like a boutique brand or specialty shop.',
    cssApproach: 'Tailwind with custom warm color palette. Soft shadows via box-shadow.',
    heroPattern: 'Warm full-width image with a cream-colored overlay card positioned asymmetrically, containing a serif headline and short poetic description.',
    sectionVariations: ['Two-column with rounded image and flowing text', 'Three-card grid with organic shadow and cream backgrounds', 'Full-bleed earth-tone image with minimal overlaid text', 'Testimonial with large serif quote marks and botanical accent'],
    signatureElements: ['Subtle grain/noise texture overlay on backgrounds', 'Botanical line-art illustrations as dividers', 'Rounded pill-shaped buttons with soft shadows', 'Muted gold accents for links and highlights'],
    typographicScale: 'Display: 3.5rem, H1: 2.5rem, H2: 1.75rem, Body: 1.05rem, Caption: 0.8rem',
    colorUsageRules: 'Cream is the primary background. Terracotta for headlines and primary CTA. Sage green for secondary elements and tags. Brown for body text. Gold sparingly for links and decorative lines.',
  },
  {
    name: 'neon-cyberpunk',
    colorPalette: 'Deep black (#0a0a0a) with electric cyan (#00f0ff), hot magenta (#ff00aa), acid green (#39ff14). No whites.',
    typography: 'Futuristic sans-serif (Orbitron or Rajdhani) for headings. Monospace (JetBrains Mono) for body. Glowing text-shadow effects.',
    layoutStyle: 'Dark panels with neon border glow, glitch effects, scanline overlays, diagonal cuts, layered z-depth.',
    density: 'dense',
    mood: 'High-tech dystopian, hacker aesthetic. Blade Runner meets Tokyo nightlife. Electric and dangerous.',
    cssApproach: 'Heavy custom CSS for glow effects (box-shadow, text-shadow, animation keyframes). Scanline overlays via repeating-linear-gradient.',
    heroPattern: 'Dark viewport with animated neon grid floor fading into distance. Glitching headline in cyan with magenta shadow offset. Pulsing CTA button with glow trail.',
    sectionVariations: ['Card grid with neon border-glow on hover', 'Terminal-style scrolling text feed', 'Split panel with diagonal neon divider line', 'Stats dashboard with glowing chart elements'],
    signatureElements: ['Scanline overlay via CSS repeating-linear-gradient', 'CSS glitch animation on key headings', 'Neon underline that pulses on hover', 'Corner bracket decorations on cards like HUD elements'],
    typographicScale: 'Display: 4rem, H1: 2.5rem, H2: 1.5rem, Body: 0.9rem mono, Caption: 0.75rem',
    colorUsageRules: 'Black background everywhere. Cyan for primary text and borders. Magenta for CTAs and interactive highlights. Acid green only for success states and data. Never use light backgrounds.',
  },
  {
    name: 'clean-corporate',
    colorPalette: 'Navy (#1e3a5f), white (#ffffff), light gray (#f4f6f8), slate (#64748b), blue accent (#2563eb).',
    typography: 'System sans-serif stack or Inter for everything. Medium weight headings, regular body. Professional and readable.',
    layoutStyle: 'Structured grid with generous gutters, card-based sections, consistent spacing, clear hierarchy.',
    density: 'balanced',
    mood: 'Professional, trustworthy, no-nonsense. Enterprise SaaS, fintech, consulting firm.',
    cssApproach: 'Pure Tailwind. Card components with subtle ring-1 borders. Standard spacing scale.',
    heroPattern: 'White background, left-aligned headline with blue accent word, short subtitle, two buttons (primary blue, secondary outline). Right side has a clean product screenshot or abstract illustration.',
    sectionVariations: ['Three-column feature cards with icon, title, description', 'Two-column split with text left and visual right', 'Stats bar with large numbers and labels', 'Logo grid of partners/clients'],
    signatureElements: ['Subtle blue accent line under active nav item', 'Card hover with slight lift shadow', 'Consistent 8px-based spacing throughout', 'Small pill badges for categories and tags'],
    typographicScale: 'Display: 3rem, H1: 2.25rem, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'White is primary background. Light gray for alternating sections. Navy for headings. Slate for body text. Blue accent exclusively for CTAs, links, and active states.',
  },
  {
    name: 'dark-hacker',
    colorPalette: 'Terminal black (#0d1117), phosphor green (#00ff41), dim green (#3fb950), dark gray (#161b22), amber (#ffa500) for warnings.',
    typography: 'Monospace only (JetBrains Mono or Fira Code). No serif, no sans-serif. Terminal aesthetic.',
    layoutStyle: 'Terminal windows with title bars, scrolling text, blinking cursors, code blocks, ASCII art borders.',
    density: 'dense',
    mood: 'Deep terminal, hacker culture, command-line interface. Matrix vibes without being cliche.',
    cssApproach: 'Custom CSS for terminal chrome, blinking animations, and scanline effects.',
    heroPattern: 'Full-screen terminal window with ASCII art logo, blinking cursor, and simulated boot sequence that types out the site description character by character.',
    sectionVariations: ['Side-by-side terminal windows showing different data', 'Scrolling log output with color-coded entries', 'ASCII-bordered content blocks', 'Tree-view file explorer layout'],
    signatureElements: ['Blinking cursor animation', 'Typed-out text reveal on scroll', 'ASCII art dividers and borders', 'Green-on-black color scheme with amber for warnings'],
    typographicScale: 'Display: 2rem mono, H1: 1.5rem mono, H2: 1.2rem mono, Body: 0.9rem mono, Caption: 0.75rem mono',
    colorUsageRules: 'Black background only. Phosphor green for primary text and borders. Dim green for secondary/muted text. Amber exclusively for warnings and highlights. No other colors.',
  },
  {
    name: 'luxury-dark',
    colorPalette: 'Charcoal (#1a1a1a), warm black (#0f0f0f), gold (#c9a84c), cream (#f0e6d2), silver (#c0c0c0).',
    typography: 'Elegant serif (Cormorant Garamond or Playfair Display) for headlines. Thin sans-serif (Montserrat Light) for body. Wide letter-spacing on uppercase labels.',
    layoutStyle: 'Full-bleed imagery, cinematic aspect ratios, generous negative space, thin gold lines as dividers.',
    density: 'sparse',
    mood: 'High-end fashion, luxury watches, premium real estate. Cinematic, aspirational, exclusive.',
    cssApproach: 'Custom CSS for cinematic image treatments, gold gradient borders, and smooth parallax-like scroll animations.',
    heroPattern: 'Full-viewport cinematic image (dark, moody) with a single elegant serif headline centered, thin gold horizontal line above, and a small uppercase CTA below.',
    sectionVariations: ['Large image with offset cream text card overlapping', 'Horizontal scroll gallery of products', 'Centered narrow text column with generous margins', 'Split screen: dark image left, gold-accented text right'],
    signatureElements: ['Thin gold lines (1px) as section dividers', 'Uppercase tracking-widest labels', 'Images with dark vignette overlay', 'Fade-in-up GSAP animations on scroll'],
    typographicScale: 'Display: 4.5rem serif, H1: 3rem serif, H2: 1.75rem serif, Body: 0.95rem sans, Caption: 0.75rem uppercase tracking-wide',
    colorUsageRules: 'Warm black is primary background. Charcoal for cards/panels. Gold exclusively for accents: lines, icons, hover states. Cream for headline text. Silver for body text and secondary info.',
  },
  {
    name: 'retro-synthwave',
    colorPalette: 'Deep navy (#0b0b2e), sunset pink (#ff6b9d), chrome (#e0e0ff), neon blue (#4cc9f0), orange (#ff6d00).',
    typography: 'Retro display font (Bungee or Righteous) for headlines. Clean sans (Quicksand) for body. All-caps headlines.',
    layoutStyle: 'Sunset gradient backgrounds, grid floor perspective, chrome text effects, 80s-inspired geometric shapes.',
    density: 'balanced',
    mood: '80s nostalgia, retro-future, outrun aesthetic. Neon sunsets and chrome reflections.',
    cssApproach: 'Custom CSS for gradient backgrounds, perspective grid, and chrome text effects. Mix with Tailwind layout.',
    heroPattern: 'Sunset gradient background (navy to pink to orange) with a chrome/metallic headline, perspective grid floor vanishing into horizon, geometric sun shape.',
    sectionVariations: ['Cards on gradient background with chrome borders', 'Horizontal feature strip with neon icons', 'Full-width parallax sunset scene', 'Grid of items with hover glow effect'],
    signatureElements: ['Sunset gradient (navy > pink > orange) backgrounds', 'Chrome/metallic text effect via linear-gradient on text', 'Perspective grid floor', 'Geometric shapes: triangles, circles floating as decoration'],
    typographicScale: 'Display: 4rem uppercase, H1: 2.5rem uppercase, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'Navy is primary background. Sunset gradient for hero sections and accents. Pink for primary CTAs. Chrome for headlines. Neon blue for links and interactive elements.',
  },
  {
    name: 'glassmorphism-modern',
    colorPalette: 'Gradient mesh background (soft blue #dbeafe, soft pink #fce7f3, soft green #d1fae5). White glass panels. Dark text (#1e293b).',
    typography: 'Modern geometric sans (Plus Jakarta Sans or Satoshi). Semi-bold headings. Regular body.',
    layoutStyle: 'Frosted glass cards (backdrop-blur-xl, bg-white/30), rounded-3xl corners, soft colored shadows, floating elements.',
    density: 'balanced',
    mood: 'Modern iOS-inspired, clean and airy. Startup landing page, design tool, creative SaaS.',
    cssApproach: 'Tailwind with backdrop-blur utilities. Custom gradient mesh backgrounds.',
    heroPattern: 'Animated gradient mesh background with a centered frosted glass card containing headline, subtitle, and CTA. Floating abstract shapes behind the glass.',
    sectionVariations: ['Grid of glass cards with colored icon backgrounds', 'Glass panel with tabbed content inside', 'Full-width glass strip with stats', 'Stacked glass cards with slight overlap'],
    signatureElements: ['backdrop-blur-xl bg-white/30 on all cards', 'Soft multi-color shadows (shadow-blue-200/50)', 'Animated gradient mesh background', 'Rounded-3xl everywhere for extra softness'],
    typographicScale: 'Display: 3.5rem, H1: 2.5rem, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'Gradient mesh is the base background. All content sits on frosted glass panels. Use dark slate text for readability. Colored shadows match nearest gradient hue. CTAs are solid colors that complement the gradient.',
  },
  {
    name: 'magazine-editorial',
    colorPalette: 'Off-white (#fafaf7), near-black (#1a1a1a), warm gray (#6b6b6b), accent red (#c43a31).',
    typography: 'Strong serif (Fraunces or Newsreader) for headlines. Clean sans (Source Sans 3) for body. Large headline sizes with tight line-height.',
    layoutStyle: 'Asymmetric multi-column layouts, full-bleed images, pull quotes, drop caps, editorial grid.',
    density: 'balanced',
    mood: 'High-end print magazine brought to digital. Bold editorial voice, strong imagery, confident typography.',
    cssApproach: 'CSS Grid for editorial layouts. Custom first-letter drop caps. Mix of Tailwind and custom.',
    heroPattern: 'Full-bleed hero image with bold serif headline overlaid in white or near-black. Small category label above headline. Author byline and date below.',
    sectionVariations: ['Asymmetric two-column with large image and narrow text', 'Pull quote with oversized serif quotation marks', 'Masonry grid of varying-height article cards', 'Full-width image break with caption'],
    signatureElements: ['Drop cap on first paragraph', 'Thin horizontal rules between sections', 'Category labels in uppercase tracking-wide', 'Large pull quotes with decorative quotation marks'],
    typographicScale: 'Display: 4.5rem tight, H1: 3rem tight, H2: 1.75rem, Body: 1.1rem with 1.8 line-height, Caption: 0.75rem',
    colorUsageRules: 'Off-white is primary background. Near-black for all text. Warm gray for secondary text and captions. Accent red sparingly: category labels, drop caps, and one highlight per section.',
  },
  {
    name: 'sci-fi-interface',
    colorPalette: 'Deep space (#05060f), interface blue (#1a8fff), panel dark (#0a1628), grid cyan (#00e5ff), alert orange (#ff8a00).',
    typography: 'Technical sans (Exo 2 or Chakra Petch) for headings. Small monospace for data readouts. Uppercase labels.',
    layoutStyle: 'HUD-style overlays, hexagonal patterns, corner-bracket decorations, dense data panels, radar/scanner elements.',
    density: 'dense',
    mood: 'Space command center, military sci-fi, The Expanse or Halo interface. Functional and immersive.',
    cssApproach: 'Heavy custom CSS for HUD elements, hexagonal clip-paths, animated scanning lines, and data readouts.',
    heroPattern: 'Dark viewport with animated scanning line sweeping across. Central command display with bracketed headline, status indicators, and holographic-style data readout.',
    sectionVariations: ['Data dashboard with multiple small panels and charts', 'Hex-grid layout of interactive modules', 'Scrolling log/feed with timestamp prefix', 'Full-width tactical map or radar display'],
    signatureElements: ['Corner bracket decorations on panels: before/after pseudo-elements', 'Animated scanning line (horizontal gradient moving across)', 'Hexagonal clip-path on images/avatars', 'Small blinking status dots (green/orange/red)'],
    typographicScale: 'Display: 2.5rem uppercase tracking-wide, H1: 1.75rem uppercase, H2: 1.25rem, Body: 0.85rem, Caption: 0.7rem mono',
    colorUsageRules: 'Deep space is primary background. Panel dark for card backgrounds. Interface blue for borders, labels, and primary interactive elements. Cyan for highlights and focus states. Orange for alerts and warnings only.',
  },
  {
    name: 'minimal-zen',
    colorPalette: 'Pure white (#ffffff), near-black (#111), light warm gray (#e8e4df), stone (#a09888).',
    typography: 'Thin weight sans-serif (Inter Thin or Nunito Light) for headings. Regular weight for body. Maximum readability.',
    layoutStyle: 'Extreme whitespace. Single column centered. No visual clutter. Every element breathes.',
    density: 'sparse',
    mood: 'Calm, meditative, Japanese-inspired minimalism. Less is more. Every pixel is intentional.',
    cssApproach: 'Minimal Tailwind. Very few classes per element. Custom spacing via margin.',
    heroPattern: 'White page with a single centered line of thin text. Massive whitespace above and below. Perhaps a single thin horizontal line or small stone-colored circle as the only visual element.',
    sectionVariations: ['Single narrow column of flowing text', 'One large image with small caption below', 'Centered list of links with generous spacing', 'Two items side by side with extreme gap between'],
    signatureElements: ['Extreme padding and margins (py-32, px-16)', 'Thin 1px lines as the only decoration', 'Fade-in animations that are barely perceptible', 'Near-invisible hover state changes'],
    typographicScale: 'Display: 2.5rem thin, H1: 1.75rem thin, H2: 1.25rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'Pure white background. Near-black for text. Stone for secondary text and captions. Warm gray only for subtle divider lines. No accent colors. No colored backgrounds.',
  },
  {
    name: 'gaming-esports',
    colorPalette: 'Black (#0a0a0a), red (#ef4444), bright yellow (#facc15), white (#fff), dark gray (#1f1f1f).',
    typography: 'Bold condensed sans (Oswald or Barlow Condensed). All-caps headings. Aggressive sizing.',
    layoutStyle: 'Angular clip-paths, diagonal sections, dynamic grid, bold borders, high contrast.',
    density: 'dense',
    mood: 'Competitive gaming, esports tournaments, PC hardware. Energy, speed, aggression.',
    cssApproach: 'Tailwind with clip-path polygons via custom CSS. Diagonal section dividers.',
    heroPattern: 'Dark background with red angular overlay. Giant bold condensed headline at an angle. Action imagery with color dodge blending. Prominent tournament/play CTA.',
    sectionVariations: ['Angled card grid with hover scale', 'Live score ticker strip', 'Player/team cards with clip-path shapes', 'Diagonal section divider with stats below'],
    signatureElements: ['clip-path: polygon() on images and sections for angular cuts', 'Diagonal divider lines between sections', 'Skew transforms on hover for dynamic feel', 'Bold outline borders on buttons and cards'],
    typographicScale: 'Display: 5rem condensed uppercase, H1: 3rem condensed uppercase, H2: 1.5rem, Body: 0.95rem, Caption: 0.75rem uppercase',
    colorUsageRules: 'Black background. Red for primary accents, borders, and CTAs. Yellow for secondary highlights and badges. White for text. Dark gray for card backgrounds. Never mix red and yellow in same element.',
  },
  {
    name: 'scandinavian-clean',
    colorPalette: 'White (#ffffff), warm wood (#c4a882), charcoal (#333), soft sage (#b5c4b1), light beige (#f5f1eb).',
    typography: 'Clean geometric sans (Manrope or Albert Sans). Light/medium weight. Comfortable reading sizes.',
    layoutStyle: 'Clean grid, functional layout, natural photography, muted tones, deliberate simplicity.',
    density: 'balanced',
    mood: 'Nordic design: functional, honest, beautiful in simplicity. Furniture brand, lifestyle, architecture.',
    cssApproach: 'Tailwind with custom color palette. Clean grid via CSS Grid.',
    heroPattern: 'Light background with large product/lifestyle photograph. Clean sans headline below or beside it. Minimal CTA button in charcoal.',
    sectionVariations: ['Two-column product grid with generous spacing', 'Single hero image with short description below', 'Horizontal scroll of lifestyle images', 'Clean specs/details table with alternating beige rows'],
    signatureElements: ['Natural wood-tone accents', 'Rounded-lg (not 3xl) for subtle softness', 'Photography with natural lighting and muted colors', 'Generous line-height and letter-spacing for readability'],
    typographicScale: 'Display: 3rem, H1: 2.25rem, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'White primary background. Beige for alternating sections. Charcoal for text. Wood tone for accents and hover states. Sage for tags and secondary CTAs.',
  },
  {
    name: 'art-deco-gatsby',
    colorPalette: 'Rich black (#0d0d0d), gold (#d4a853), cream (#f4ecd8), deep emerald (#004d40), champagne (#f7e7ce).',
    typography: 'Art Deco display (Poiret One) for headlines. Elegant serif (EB Garamond) for body. Uppercase spaced headings.',
    layoutStyle: 'Geometric symmetry, gold borders, fan motifs, symmetrical layouts, strong vertical lines.',
    density: 'balanced',
    mood: '1920s glamour, jazz age, Gatsby parties. Opulent, geometric, golden.',
    cssApproach: 'Custom CSS for geometric patterns, gold borders, and decorative elements. Tailwind for layout.',
    heroPattern: 'Black background with gold geometric border frame. Centered headline in art deco typeface. Sunburst pattern radiating from center. Gold horizontal rules above and below.',
    sectionVariations: ['Symmetrical three-column with gold divider lines', 'Full-width gold-bordered feature panel', 'Grid of items with geometric gold corner ornaments', 'Centered narrow column with decorative gold borders'],
    signatureElements: ['Gold sunburst/fan motifs as section dividers', 'Geometric gold corner decorations on panels', 'Thin gold double-line borders', 'Symmetrical layout with strong center axis'],
    typographicScale: 'Display: 4rem uppercase tracking-widest, H1: 2.5rem uppercase, H2: 1.5rem, Body: 1rem serif, Caption: 0.8rem uppercase tracking-wide',
    colorUsageRules: 'Rich black background. Gold for all decorative elements, borders, and accents. Cream for text. Emerald sparingly for secondary panels or CTAs. Champagne for subtle highlights.',
  },
  {
    name: 'pastel-soft',
    colorPalette: 'Baby pink (#fce4ec), lavender (#e8eaf6), mint (#e0f2f1), soft yellow (#fff9c4), white (#fff).',
    typography: 'Rounded sans-serif (Nunito or Quicksand). Medium weight. Friendly and approachable sizing.',
    layoutStyle: 'Rounded corners (20-28px), soft shadows, pastel gradients, playful but clean layout.',
    density: 'balanced',
    mood: 'Soft, friendly, approachable. Beauty brand, wellness app, children education, creative platform.',
    cssApproach: 'Tailwind with pastel color palette. Rounded-2xl and rounded-3xl. Soft drop shadows.',
    heroPattern: 'Soft pastel gradient background (pink to lavender). Rounded card with friendly headline, cute illustration or icon, and a pastel-colored CTA button.',
    sectionVariations: ['Pastel card grid with different background tints', 'Rounded feature blocks with large icons', 'Horizontal scroll of pastel-tinted testimonial cards', 'Centered CTA section with soft gradient background'],
    signatureElements: ['Pastel gradient backgrounds that shift between sections', 'Large rounded icons in soft colored circles', 'Subtle blob shapes as background decoration', 'Bouncy micro-animations on hover'],
    typographicScale: 'Display: 3rem, H1: 2.25rem, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'White primary background. Different pastels for each section background. Dark text (#374151) for contrast. Use one pastel per section, never mix multiple pastels in the same card. CTAs use darker saturated versions of the section pastel.',
  },
  {
    name: 'data-dashboard',
    colorPalette: 'Dark slate (#0f172a), card dark (#1e293b), chart blue (#3b82f6), chart green (#22c55e), chart orange (#f97316), chart red (#ef4444), text gray (#94a3b8).',
    typography: 'UI sans-serif (Inter) for everything. Tabular numbers for data. Small-medium sizing for density.',
    layoutStyle: 'Dense grid of data panels, charts, tables. Sidebar navigation. Compact spacing. Status indicators.',
    density: 'dense',
    mood: 'Analytical, data-driven, professional tool. SaaS dashboard, monitoring platform, analytics.',
    cssApproach: 'Tailwind grid. Chart.js for data visualization. Compact spacing via gap-2, p-3.',
    heroPattern: 'No traditional hero. Top bar with key metrics (large numbers with trend arrows), followed immediately by a grid of chart panels and data tables.',
    sectionVariations: ['2x2 chart grid with line/bar/pie/donut', 'Data table with sortable columns and row hover', 'KPI cards row with sparkline charts', 'Activity feed sidebar with timestamps'],
    signatureElements: ['Color-coded status dots (green/orange/red)', 'Trend arrows (up green, down red) next to metrics', 'Compact 4px-based spacing for data density', 'Subtle ring-1 borders on all panels'],
    typographicScale: 'Display: 2rem, H1: 1.5rem, H2: 1.15rem, Body: 0.875rem, Caption: 0.75rem, Data: 1.5rem tabular-nums',
    colorUsageRules: 'Dark slate background. Card dark for panels. Each chart series uses a designated color from the chart palette. Text gray for labels. White for primary values. Colored indicators only for status and trends.',
  },
  {
    name: 'nature-botanical',
    colorPalette: 'Forest green (#1a3c2a), cream (#faf8f0), leaf green (#4a7c59), warm brown (#8b6f47), blush (#e8c4b8).',
    typography: 'Organic serif (Lora or Crimson Text) for headings. Soft sans (Source Sans 3) for body.',
    layoutStyle: 'Flowing sections, organic curved shapes, botanical illustrations, natural photography.',
    density: 'balanced',
    mood: 'Botanical garden, eco brand, organic products, nature reserve. Green, earthy, alive.',
    cssApproach: 'Custom CSS for curved section dividers (SVG waves). Tailwind for layout.',
    heroPattern: 'Full-bleed nature photograph with cream overlay from bottom. Serif headline in forest green. Organic leaf illustration as accent.',
    sectionVariations: ['Curved section divider with organic shape', 'Two-column with botanical illustration alongside text', 'Card grid with leaf-green accents and cream backgrounds', 'Full-width image band with quote overlay'],
    signatureElements: ['SVG curved/wave section dividers', 'Botanical line-art illustrations', 'Subtle leaf pattern as background texture', 'Organic rounded shapes (not geometric circles)'],
    typographicScale: 'Display: 3.5rem serif, H1: 2.5rem serif, H2: 1.75rem, Body: 1.05rem, Caption: 0.8rem',
    colorUsageRules: 'Cream primary background. Forest green for headings and primary CTAs. Leaf green for secondary accents. Warm brown for body text. Blush sparingly for highlight backgrounds.',
  },
  {
    name: 'neo-brutalism',
    colorPalette: 'White (#fff), black (#000), electric blue (#0066ff), bright yellow (#ffe600), hot pink (#ff3366).',
    typography: 'Bold chunky sans (Space Grotesk Bold or Archivo Black). Very large headings. Regular weight body.',
    layoutStyle: 'Thick black borders (3-4px), solid color blocks, offset box-shadows, blocky rounded-xl shapes, visible outlines.',
    density: 'balanced',
    mood: 'Playful brutalism. Bold, fun, unapologetic. Modern startup, creative tool, portfolio.',
    cssApproach: 'Tailwind with custom border and shadow utilities. Shadow-[4px_4px_0_#000] for offset shadows.',
    heroPattern: 'White background with large bold headline in black. Offset color blocks behind key words. Thick-bordered CTA button with offset black shadow. Playful illustration or sticker-like graphic.',
    sectionVariations: ['Chunky card grid with thick borders and color-coded shadows', 'Color-blocked feature sections alternating yellow/blue/pink', 'Sticker-style floating elements with rotation', 'Bold stats section with large numbers and colored underlines'],
    signatureElements: ['4px solid black borders on everything', 'Offset box-shadow: 4px 4px 0 #000', 'Solid background color blocks (no gradients)', 'Slight rotation (rotate-1, -rotate-1) on cards for playful feel'],
    typographicScale: 'Display: 5rem bold, H1: 3rem bold, H2: 1.75rem bold, Body: 1.05rem, Caption: 0.8rem',
    colorUsageRules: 'White primary background. Use one bright color per section as accent. Black borders and shadows on everything. Never use gradients. Colors should feel like markers on paper.',
  },
  {
    name: 'dark-academia',
    colorPalette: 'Deep brown (#1c1712), warm parchment (#e8dcc8), aged gold (#b8943e), burgundy (#6b2737), olive (#5c5c3d).',
    typography: 'Classic serif (EB Garamond or Libre Baskerville) for everything. Italic for emphasis. Traditional sizing.',
    layoutStyle: 'Book-like layout, decorative borders, classical proportions, rich textures, scholarly feel.',
    density: 'balanced',
    mood: 'Scholarly, mysterious, romantic. Old libraries, hidden knowledge, classical education.',
    cssApproach: 'Custom CSS for parchment textures and decorative borders. Serif-heavy typography.',
    heroPattern: 'Dark brown background with parchment-colored text area. Large serif headline with subtle gold ornament above. Classical border frame around content area.',
    sectionVariations: ['Two-column like an open book spread', 'Ornamental bordered text panel on dark background', 'Catalogue-style grid with classical numbering', 'Quote block with decorative rules and italic text'],
    signatureElements: ['Ornamental horizontal rules (decorative dividers)', 'Drop caps in gold or burgundy', 'Subtle parchment texture background', 'Classical proportions: narrow content column (600px max)'],
    typographicScale: 'Display: 3rem serif, H1: 2.25rem serif, H2: 1.5rem serif, Body: 1.05rem serif, Caption: 0.8rem italic',
    colorUsageRules: 'Deep brown or parchment backgrounds (alternating). Gold for decorative accents and ornaments. Burgundy for links and emphasis. Olive for secondary accents. Body text in deep brown on parchment, or parchment on deep brown.',
  },
  {
    name: 'tropical-vibrant',
    colorPalette: 'Teal (#0d9488), coral (#f97316), hot pink (#ec4899), sunny yellow (#fbbf24), white (#fff), dark teal (#134e4a).',
    typography: 'Fun rounded sans (Nunito or Poppins). Bold headings. Generous sizing and spacing.',
    layoutStyle: 'Colorful sections, organic shapes, tropical photography, bold color blocks, lively animations.',
    density: 'balanced',
    mood: 'Vacation, tropical resort, summer festival, food/drink brand. Vibrant, joyful, energetic.',
    cssApproach: 'Tailwind with custom color palette. Organic blob shapes via SVG or border-radius. Lively GSAP animations.',
    heroPattern: 'Bright teal or gradient background with large tropical photograph. Bold white headline with fun personality. Coral CTA button. Organic wave divider at bottom.',
    sectionVariations: ['Colorful card grid with each card a different vibrant background', 'Full-bleed tropical photo with overlaid text', 'Wave-divided sections alternating white and colored backgrounds', 'Circular image gallery with bold colored borders'],
    signatureElements: ['SVG wave/organic shape section dividers', 'Bold background color transitions between sections', 'Tropical photography with high saturation', 'Circular and organic shapes instead of rectangles'],
    typographicScale: 'Display: 3.5rem bold, H1: 2.5rem bold, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'White primary background. Each section uses one vibrant color as its accent. Teal for nav and footer. Coral for primary CTAs. Never use more than two bright colors in the same section.',
  },
  {
    name: 'monochrome-editorial',
    colorPalette: 'Black (#000000), white (#ffffff), dark gray (#222222), medium gray (#666666), light gray (#cccccc).',
    typography: 'Refined serif (Cormorant Garamond) for headlines. Thin sans (Inter Light) for body. Dramatic size contrast.',
    layoutStyle: 'High-contrast black/white photography, dramatic layouts, gallery-like spacing, print-inspired.',
    density: 'sparse',
    mood: 'Sophisticated photography portfolio, fashion editorial, architectural showcase. Dramatic and artistic.',
    cssApproach: 'Minimal CSS. Heavy reliance on grayscale images and whitespace. Custom grid for dramatic layouts.',
    heroPattern: 'Full-bleed black-and-white photograph filling viewport. Single word or short headline in white, positioned dramatically (bottom-left or centered). No other elements.',
    sectionVariations: ['Large single image with generous whitespace', 'Asymmetric text-image layout with extreme offset', 'Narrow centered text column between full-bleed images', 'Horizontal scroll of dramatic black-and-white photographs'],
    signatureElements: ['All imagery in black and white (grayscale filter)', 'Dramatic size contrast between hero elements and body text', 'Extreme whitespace as a design element', 'Thin lines (0.5px) as the only decorative elements'],
    typographicScale: 'Display: 6rem thin serif, H1: 3.5rem thin, H2: 1.75rem, Body: 0.95rem light, Caption: 0.7rem uppercase tracking-widest',
    colorUsageRules: 'Strictly black, white, and gray. No accent colors at all. Use grayscale for all imagery. Contrast comes from scale and weight, not color.',
  },
  {
    name: 'retro-90s',
    colorPalette: 'Teal (#008080), magenta (#ff00ff), lime (#00ff00), default gray (#c0c0c0), bright yellow (#ffff00).',
    typography: 'Comic Sans or Times New Roman for headers. Arial for body. Classic web fonts. Pixel-friendly sizes.',
    layoutStyle: 'Table-based layout feel, beveled borders, hit counters, animated GIFs aesthetic, visible frames.',
    density: 'dense',
    mood: 'GeoCities, Angelfire, early web nostalgia. Chaotic, fun, digital DIY culture.',
    cssApproach: 'Custom CSS mimicking 90s web. Beveled borders, background patterns, outset/inset box-shadows.',
    heroPattern: 'Tiled background pattern. Centered title in large colorful text with shadow. Animated "under construction" or "welcome" banner. Hit counter at bottom.',
    sectionVariations: ['Table-layout grid with visible cell borders', 'Sidebar with link collection and bullet points', 'Guestbook-style comment section', 'Animated marquee text banner'],
    signatureElements: ['Beveled/embossed borders via outset box-shadow', 'Tiled background patterns', 'Animated marquee elements', 'Visible table borders and cell padding'],
    typographicScale: 'Display: 2rem, H1: 1.5rem, H2: 1.2rem, Body: 0.9rem, Caption: 0.75rem',
    colorUsageRules: 'Gray default background. Teal for links. Bright colors used liberally and clashingly on purpose. No design system consistency. Embrace visual chaos.',
  },
  {
    name: 'newspaper-classic',
    colorPalette: 'Newsprint (#f5f0e8), ink black (#1a1a1a), red (#cc0000), dark gray (#444444).',
    typography: 'Traditional serif (Merriweather or Noto Serif) for body. Bold condensed serif for headlines. Classic newspaper hierarchy.',
    layoutStyle: 'Multi-column layout, justified text, above-the-fold hierarchy, section dividers, dateline headers.',
    density: 'dense',
    mood: 'Broadsheet newspaper, print journalism, classic news. Authoritative and structured.',
    cssApproach: 'CSS columns for text flow. Custom borders and rules. Traditional grid.',
    heroPattern: 'Newspaper-style masthead with name and dateline. Large headline spanning full width. Below-the-fold multi-column layout begins immediately.',
    sectionVariations: ['Three-column text layout with vertical rules between', 'Lead story with large image and column wrap', 'Sidebar with breaking news items', 'Classified-ad style grid of small items'],
    signatureElements: ['Vertical rules between columns', 'Justified text with hyphenation', 'Newspaper-style dateline and edition info', 'Thin horizontal rules between stories'],
    typographicScale: 'Display: 3rem serif condensed, H1: 2rem serif, H2: 1.25rem serif, Body: 0.95rem serif justified, Caption: 0.75rem',
    colorUsageRules: 'Newsprint background. Ink black for all text. Red only for breaking news labels and section headers. Dark gray for bylines and datelines.',
  },
  {
    name: 'vintage-letterpress',
    colorPalette: 'Aged paper (#e8dcc8), ink brown (#3a2a1a), rust (#a0522d), deep forest (#2d4a3e), faded blue (#5a7a8a).',
    typography: 'Handwritten or vintage display (Playfair Display or Spectral) for headlines. Traditional serif for body. Decorative initials.',
    layoutStyle: 'Centered layouts, ornamental borders, vintage badges, hand-drawn line art, stamp-like elements.',
    density: 'balanced',
    mood: 'Old print shop, vintage apothecary, craft brewery, artisanal brand. Aged and authentic.',
    cssApproach: 'Custom CSS for textures, ornamental borders, and badge elements.',
    heroPattern: 'Aged paper background with centered ornamental border frame. Vintage-style headline with decorative swashes. Small tagline in italic. Badge or seal element.',
    sectionVariations: ['Centered text block with ornamental top and bottom borders', 'Vintage badge/seal as section accent', 'Three-column with decorative vertical dividers', 'Price list or menu in classical table format'],
    signatureElements: ['Ornamental border frames', 'Vintage badge/seal illustrations', 'Decorative swashes on headings', 'Paper texture background'],
    typographicScale: 'Display: 3rem serif, H1: 2.25rem serif, H2: 1.5rem, Body: 1rem serif, Caption: 0.8rem italic',
    colorUsageRules: 'Aged paper background. Ink brown for primary text. Rust for accents and decorative elements. Deep forest for secondary panels. Faded blue for links.',
  },
  {
    name: 'comic-pop-art',
    colorPalette: 'Bright yellow (#ffe600), bold red (#ff0000), vivid blue (#0066cc), white (#fff), black (#000).',
    typography: 'Comic-style display (Bangers or Bungee Shade) for headlines. Clean bold sans for body.',
    layoutStyle: 'Comic panel grid, halftone patterns, speech bubble elements, bold outlines, dynamic angles.',
    density: 'dense',
    mood: 'Pop art, comic book, Lichtenstein-inspired. Bold, fun, energetic, camp.',
    cssApproach: 'Custom CSS for halftone patterns (radial-gradient dots), speech bubbles, and thick outlines.',
    heroPattern: 'Comic-panel style hero with bold outlined text. Halftone dot pattern background. Speech bubble containing the main message. Action lines radiating from center.',
    sectionVariations: ['Comic panel grid layout with thick black borders', 'Speech bubble testimonials', 'Halftone-patterned background sections', 'Starburst/explosion shapes around key content'],
    signatureElements: ['Halftone dot pattern backgrounds via radial-gradient', 'Thick 3px black outlines on everything', 'Speech bubble shapes via CSS border-radius and triangles', 'Action words (POW! ZAP!) as decorative elements'],
    typographicScale: 'Display: 4rem bold, H1: 2.5rem bold, H2: 1.5rem, Body: 1rem, Caption: 0.8rem',
    colorUsageRules: 'White or yellow primary background. Red for CTAs and accents. Blue for secondary elements and links. Black outlines on everything. Halftone patterns in one color per section.',
  },
  {
    name: 'government-official',
    colorPalette: 'Navy (#1a2744), white (#ffffff), light gray (#f0f2f5), medium blue (#2563eb), dark text (#1f2937).',
    typography: 'Accessible sans-serif (Public Sans or Noto Sans). Clear hierarchy. 16px minimum body text.',
    layoutStyle: 'Structured, accessible, well-organized. Header banner, breadcrumbs, sidebar nav, content area.',
    density: 'balanced',
    mood: 'Government, institution, public service. Trustworthy, accessible, formal.',
    cssApproach: 'Tailwind with focus on accessibility. ARIA labels. Skip navigation. High contrast.',
    heroPattern: 'Navy header banner with white institution name and seal/logo. Below: breadcrumb trail, then white content area with clear headline.',
    sectionVariations: ['Card grid of services with icons', 'Sidebar navigation with content area', 'Alert/notice banner at top of content', 'Structured form with clear labels and validation'],
    signatureElements: ['Navy header banner', 'Skip-navigation link', 'Focus-visible outlines on all interactive elements', 'US Web Design System-inspired components'],
    typographicScale: 'Display: 2.5rem, H1: 2rem, H2: 1.5rem, Body: 1rem (min 16px), Caption: 0.875rem',
    colorUsageRules: 'White primary background. Navy for header and footer. Light gray for sidebar. Medium blue for links and CTAs. Dark text for body. High contrast ratios required (4.5:1 minimum).',
  },
  {
    name: 'playful-children',
    colorPalette: 'Bright blue (#3b82f6), sunny orange (#fb923c), grass green (#22c55e), cherry red (#ef4444), white (#fff), soft purple (#a78bfa).',
    typography: 'Rounded friendly sans (Nunito or Fredoka). Bold for headings. Large sizes for readability.',
    layoutStyle: 'Large rounded elements, colorful sections, big touch targets, playful illustrations, bouncy animations.',
    density: 'sparse',
    mood: 'Children, education, family apps. Fun, safe, colorful, encouraging.',
    cssApproach: 'Tailwind with large padding, rounded-3xl, bright colors. GSAP bouncy animations.',
    heroPattern: 'Bright colored background with large friendly illustration or mascot. Big bold headline in white or dark text. Large rounded CTA button with fun hover animation.',
    sectionVariations: ['Large colorful card grid with icons and short text', 'Activity/game sections with interactive elements', 'Character/mascot-guided tutorial steps', 'Colorful progress bars and achievement badges'],
    signatureElements: ['Rounded-3xl everywhere', 'Bouncy spring animations on hover/click', 'Large touch-friendly buttons (min 48px)', 'Bright contrasting colors per section'],
    typographicScale: 'Display: 3rem bold, H1: 2.5rem bold, H2: 1.75rem, Body: 1.1rem, Caption: 0.9rem',
    colorUsageRules: 'White primary background. Each section uses one bright color. Text is dark gray (#374151) for readability. Buttons use the section accent color. Never use more than two colors in the same component.',
  },
  {
    name: 'industrial-tech',
    colorPalette: 'Gunmetal (#2d3436), warning orange (#e17055), steel (#dfe6e9), dark (#0d0d0d), yellow (#fdcb6e).',
    typography: 'Condensed sans (Barlow Condensed or Roboto Condensed) for headings. Regular sans for body. Uppercase labels.',
    layoutStyle: 'Angular layouts, exposed grid, industrial textures, warning stripes, heavy borders.',
    density: 'dense',
    mood: 'Industrial, manufacturing, heavy machinery, construction tech. Robust, functional, tough.',
    cssApproach: 'Custom CSS for industrial textures and warning patterns. Tailwind for grid.',
    heroPattern: 'Dark background with steel-textured header. Bold condensed headline. Warning-orange accent stripe. Technical specs or status readout below.',
    sectionVariations: ['Technical spec grid with labeled values', 'Status dashboard with warning indicators', 'Image gallery with steel-frame borders', 'Timeline/process flow with industrial aesthetic'],
    signatureElements: ['Warning stripe pattern (diagonal yellow/black)', 'Exposed bolt/rivet decorative elements', 'Heavy 2-3px borders', 'Steel/metal texture backgrounds'],
    typographicScale: 'Display: 3rem condensed uppercase, H1: 2rem condensed uppercase, H2: 1.25rem, Body: 0.95rem, Caption: 0.75rem uppercase',
    colorUsageRules: 'Gunmetal or dark primary background. Steel for text on dark backgrounds. Warning orange for CTAs and alerts. Yellow for caution elements. Never use soft or pastel colors.',
  },
];

export interface BrandPattern {
  pattern: RegExp;
  directive: string;
}

export const BRAND_PATTERNS: BrandPattern[] = [
  { pattern: /google\./i, directive: 'Google: Clean Material Design 3 aesthetic. White backgrounds, rounded search bar, colorful Google logo (blue, red, yellow, green). Subtle shadows, system font stack, 8px grid. Colorful accents.' },
  { pattern: /github\./i, directive: 'GitHub: Developer platform. Dark header (#24292f), white content area, monospace code blocks, octicon-style icons. Clean, information-dense, developer-focused.' },
  { pattern: /reddit\./i, directive: 'Reddit: Community forum. Orangered (#ff4500) accent, card-based post feed, upvote/downvote system, nested comment threads, subreddit sidebar.' },
  { pattern: /amazon\./i, directive: 'Amazon: E-commerce. Dense product grid, orange (#ff9900) CTAs, star ratings, price comparison, Buy Now buttons, recommendation carousels.' },
  { pattern: /(twitter|x)\./i, directive: 'Twitter/X: Social microblogging. Dark (#000) or white bg, blue accent (#1d9bf0), tweet cards, follow buttons, trending sidebar, character-limited posts.' },
  { pattern: /youtube\./i, directive: 'YouTube: Video platform. Red (#ff0000) accent, video thumbnail grid, subscribe buttons, watch progress bars, comment sections, channel layouts.' },
  { pattern: /wikipedia\./i, directive: 'Wikipedia: Encyclopedia. Clean white, blue links, serif body text, table of contents sidebar, edit buttons, citation footnotes, neutral encyclopedic tone.' },
  { pattern: /nytimes\./i, directive: 'NYTimes: Premium journalism. Classic serif (Cheltenham), editorial layouts, paywall indicator, section navigation, bylines with timestamps, photojournalism.' },
  { pattern: /spotify\./i, directive: 'Spotify: Music streaming. Black (#121212) background, green (#1db954) accent, album art grid, play buttons, audio player bar, playlist cards.' },
  { pattern: /netflix\./i, directive: 'Netflix: Streaming service. Dark (#141414) background, red (#e50914) accent, large hero billboard, horizontal scroll rows of content, play/info buttons.' },
  { pattern: /apple\./i, directive: 'Apple: Premium tech. White/dark toggle, SF Pro font, large hero product shots, minimalist layout, dramatic scroll animations, premium feel.' },
  { pattern: /twitch\./i, directive: 'Twitch: Live streaming. Dark (#0e0e10) bg, purple (#9146ff) accent, video player, chat panel, category browse, live indicators.' },
  { pattern: /linkedin\./i, directive: 'LinkedIn: Professional network. White bg, blue (#0a66c2) accent, professional feed, job listings, connection cards, company pages.' },
  { pattern: /stackoverflow\./i, directive: 'StackOverflow: Q&A for developers. White bg, orange (#f48024) accent, question/answer format, vote counts, code blocks, tag system.' },
  { pattern: /medium\./i, directive: 'Medium: Publishing platform. Clean white, green (#1a8917) accent, large serif text, clap button, reading time estimates, member-only indicators.' },
  { pattern: /pinterest\./i, directive: 'Pinterest: Visual discovery. Red (#e60023) accent, masonry pin grid, save buttons, board collections, visual search.' },
  { pattern: /discord\./i, directive: 'Discord: Chat platform. Dark (#36393f) bg, blurple (#5865f2) accent, channel sidebar, message list, voice channels, server icons.' },
  { pattern: /instagram\./i, directive: 'Instagram: Photo sharing. White bg, gradient accent (pink to orange to purple), photo grid, Stories circles, heart/comment buttons, Explore page.' },
  { pattern: /ebay\./i, directive: 'eBay: Auction marketplace. White bg, colorful logo, bid system, item grid, seller ratings, watch list, time-remaining countdowns.' },
  { pattern: /hacker\s?news|ycombinator/i, directive: 'Hacker News: Tech news aggregator. Minimal orange (#ff6600) header, plain text layout, simple upvote arrows, nested comments, zero styling beyond basics.' },
];

export const KEYWORD_STYLE_MAPPINGS: Record<string, string> = {
  'cyber': 'neon-cyberpunk',
  'neon': 'neon-cyberpunk',
  'hack': 'dark-hacker',
  'terminal': 'dark-hacker',
  'code': 'dark-hacker',
  'dev': 'dark-hacker',
  'dashboard': 'data-dashboard',
  'analytics': 'data-dashboard',
  'monitor': 'data-dashboard',
  'metrics': 'data-dashboard',
  'admin': 'data-dashboard',
  'zen': 'minimal-zen',
  'calm': 'minimal-zen',
  'meditat': 'minimal-zen',
  'mindful': 'minimal-zen',
  'game': 'gaming-esports',
  'esport': 'gaming-esports',
  'tournament': 'gaming-esports',
  'arena': 'gaming-esports',
  'play': 'gaming-esports',
  'luxury': 'luxury-dark',
  'premium': 'luxury-dark',
  'fashion': 'luxury-dark',
  'watch': 'luxury-dark',
  'jewel': 'luxury-dark',
  'boutique': 'warm-organic',
  'artisan': 'warm-organic',
  'handmade': 'warm-organic',
  'organic': 'warm-organic',
  'craft': 'warm-organic',
  'coffee': 'warm-organic',
  'bakery': 'warm-organic',
  'news': 'newspaper-classic',
  'journal': 'newspaper-classic',
  'gazette': 'newspaper-classic',
  'times': 'newspaper-classic',
  'daily': 'newspaper-classic',
  'sci-fi': 'sci-fi-interface',
  'space': 'sci-fi-interface',
  'stellar': 'sci-fi-interface',
  'galactic': 'sci-fi-interface',
  'colony': 'sci-fi-interface',
  'mars': 'sci-fi-interface',
  'nasa': 'sci-fi-interface',
  'synth': 'retro-synthwave',
  'retro': 'retro-synthwave',
  'vaporwave': 'retro-synthwave',
  '80s': 'retro-synthwave',
  'outrun': 'retro-synthwave',
  'nature': 'nature-botanical',
  'garden': 'nature-botanical',
  'botanical': 'nature-botanical',
  'plant': 'nature-botanical',
  'eco': 'nature-botanical',
  'forest': 'nature-botanical',
  'ocean': 'nature-botanical',
  'glass': 'glassmorphism-modern',
  'startup': 'glassmorphism-modern',
  'saas': 'glassmorphism-modern',
  'app': 'glassmorphism-modern',
  'magazine': 'magazine-editorial',
  'editorial': 'magazine-editorial',
  'blog': 'magazine-editorial',
  'story': 'magazine-editorial',
  'corp': 'clean-corporate',
  'enterprise': 'clean-corporate',
  'consult': 'clean-corporate',
  'business': 'clean-corporate',
  'finance': 'clean-corporate',
  'bank': 'clean-corporate',
  'insurance': 'clean-corporate',
  'deco': 'art-deco-gatsby',
  'gatsby': 'art-deco-gatsby',
  '1920': 'art-deco-gatsby',
  'jazz': 'art-deco-gatsby',
  'gov': 'government-official',
  'government': 'government-official',
  'public': 'government-official',
  'citizen': 'government-official',
  'kid': 'playful-children',
  'child': 'playful-children',
  'learn': 'playful-children',
  'school': 'playful-children',
  'education': 'playful-children',
  'comic': 'comic-pop-art',
  'pop-art': 'comic-pop-art',
  'cartoon': 'comic-pop-art',
  'industrial': 'industrial-tech',
  'factory': 'industrial-tech',
  'manufacture': 'industrial-tech',
  'construct': 'industrial-tech',
  'photo': 'monochrome-editorial',
  'portfolio': 'monochrome-editorial',
  'gallery': 'monochrome-editorial',
  'architect': 'monochrome-editorial',
  'pastel': 'pastel-soft',
  'beauty': 'pastel-soft',
  'wellness': 'pastel-soft',
  'skincare': 'pastel-soft',
  'spa': 'pastel-soft',
  'yoga': 'pastel-soft',
  'scandi': 'scandinavian-clean',
  'furniture': 'scandinavian-clean',
  'interior': 'scandinavian-clean',
  'home': 'scandinavian-clean',
  'decor': 'scandinavian-clean',
  'vintage': 'vintage-letterpress',
  'antique': 'vintage-letterpress',
  'apothecary': 'vintage-letterpress',
  'brewery': 'vintage-letterpress',
  'library': 'dark-academia',
  'university': 'dark-academia',
  'scholar': 'dark-academia',
  'academ': 'dark-academia',
  'book': 'dark-academia',
  'tropic': 'tropical-vibrant',
  'beach': 'tropical-vibrant',
  'island': 'tropical-vibrant',
  'resort': 'tropical-vibrant',
  'vacation': 'tropical-vibrant',
  'summer': 'tropical-vibrant',
  'restaurant': 'warm-organic',
  'food': 'warm-organic',
  'recipe': 'warm-organic',
  'cook': 'warm-organic',
  'travel': 'tropical-vibrant',
  'hotel': 'luxury-dark',
  'music': 'retro-synthwave',
  'radio': 'retro-synthwave',
  'health': 'pastel-soft',
  'fitness': 'gaming-esports',
  'crypto': 'neon-cyberpunk',
  'blockchain': 'neon-cyberpunk',
  'wedding': 'pastel-soft',
  'brutalist': 'neo-brutalism',
  'bold': 'neo-brutalism',
  'creative': 'neo-brutalism',
  'agency': 'glassmorphism-modern',
  'design': 'glassmorphism-modern',
  'ai': 'glassmorphism-modern',
  'market': 'clean-corporate',
  'shop': 'clean-corporate',
  'store': 'clean-corporate',
  'ecommerce': 'clean-corporate',
  'horror': 'dark-academia',
  'haunted': 'dark-academia',
  'mystery': 'dark-academia',
  'weather': 'glassmorphism-modern',
  'pet': 'playful-children',
  'animal': 'nature-botanical',
  'kitchen': 'warm-organic',
  'dna': 'sci-fi-interface',
  'bio': 'nature-botanical',
  'simulator': 'data-dashboard',
  'planner': 'scandinavian-clean',
  'todo': 'scandinavian-clean',
  'social': 'glassmorphism-modern',
  'chat': 'glassmorphism-modern',
  'forum': 'clean-corporate',
};

export const TLD_STYLE_DEFAULTS: Record<string, string> = {
  '.shop': 'clean-corporate',
  '.store': 'clean-corporate',
  '.market': 'clean-corporate',
  '.finance': 'clean-corporate',
  '.bank': 'clean-corporate',
  '.art': 'magazine-editorial',
  '.design': 'glassmorphism-modern',
  '.gallery': 'monochrome-editorial',
  '.museum': 'monochrome-editorial',
  '.science': 'sci-fi-interface',
  '.edu': 'scandinavian-clean',
  '.university': 'dark-academia',
  '.game': 'gaming-esports',
  '.play': 'gaming-esports',
  '.io': 'glassmorphism-modern',
  '.dev': 'dark-hacker',
  '.tech': 'glassmorphism-modern',
  '.gov': 'government-official',
  '.org': 'clean-corporate',
  '.health': 'pastel-soft',
  '.fitness': 'gaming-esports',
  '.travel': 'tropical-vibrant',
  '.vacation': 'tropical-vibrant',
  '.kitchen': 'warm-organic',
  '.recipes': 'warm-organic',
  '.garden': 'nature-botanical',
  '.eco': 'nature-botanical',
  '.luxury': 'luxury-dark',
  '.fashion': 'luxury-dark',
  '.fm': 'retro-synthwave',
  '.music': 'retro-synthwave',
  '.live': 'data-dashboard',
  '.news': 'newspaper-classic',
  '.blog': 'magazine-editorial',
  '.photo': 'monochrome-editorial',
  '.build': 'neo-brutalism',
  '.space': 'sci-fi-interface',
  '.zone': 'gaming-esports',
  '.network': 'glassmorphism-modern',
  '.ai': 'glassmorphism-modern',
  '.bio': 'nature-botanical',
  '.horror': 'dark-academia',
  '.calm': 'minimal-zen',
  '.zen': 'minimal-zen',
};
