export interface DesignMood {
  name: string;
  colorPalette: string;
  typography: string;
  layoutStyle: string;
  density: 'sparse' | 'balanced' | 'dense';
  mood: string;
  cssApproach: string;
}

export interface BrandProfile {
  domain: string;
  styleDirective: string;
}

export interface KeywordMapping {
  keyword: string;
  moodName: string;
}

export const DESIGN_MOODS: DesignMood[] = [
  {
    name: 'brutalist-editorial',
    colorPalette: 'Black, white, and one stark accent (red or yellow). High contrast, no gradients.',
    typography: 'Bold serif headlines (Playfair Display or DM Serif), monospace body text. Oversized type.',
    layoutStyle: 'Asymmetric grids, overlapping elements, raw borders, exposed structure.',
    density: 'dense',
    mood: 'Confrontational, avant-garde, unapologetic. Like a zine or art manifesto.',
    cssApproach: 'Custom CSS heavy with deliberate "ugly" choices. Thick borders, uppercase headings.',
  },
  {
    name: 'warm-organic',
    colorPalette: 'Warm earth tones: terracotta (#c2703e), sage (#8b9e7e), cream (#f5f0e8), walnut (#5c4033).',
    typography: 'Rounded sans-serif (Nunito or Quicksand) for body, hand-drawn or script accent font.',
    layoutStyle: 'Soft rounded corners (16px+), organic shapes, overlapping circles, wavy section dividers.',
    density: 'balanced',
    mood: 'Cozy, handcrafted, artisanal. Like a boutique bakery or ceramics studio.',
    cssApproach: 'Tailwind with custom border-radius values and warm color overrides.',
  },
  {
    name: 'neon-cyberpunk',
    colorPalette: 'Deep black (#0a0a0a) with neon accents: electric cyan (#00f0ff), hot magenta (#ff00aa), acid green (#39ff14).',
    typography: 'Futuristic sans-serif (Orbitron or Rajdhani). Glowing text effects via text-shadow.',
    layoutStyle: 'Dark panels with neon borders, glitch effects, scanline overlays, diagonal cuts.',
    density: 'dense',
    mood: 'High-tech dystopian, hacker aesthetic. Blade Runner meets Tokyo nightlife.',
    cssApproach: 'Heavy custom CSS for glow effects, animations, and scanline overlays.',
  },
  {
    name: 'clean-corporate',
    colorPalette: 'Navy (#1e3a5f), white, light gray (#f7f8fa), blue accent (#2563eb). Professional tones.',
    typography: 'System-style sans-serif (Inter or Source Sans 3). Clean, readable, no decoration.',
    layoutStyle: 'Strict grid system, generous padding, card-based sections, subtle shadows.',
    density: 'balanced',
    mood: 'Trustworthy, efficient, polished. Enterprise SaaS or consulting firm.',
    cssApproach: 'Tailwind-heavy with standard spacing scale. Minimal custom CSS.',
  },
  {
    name: 'playful-children',
    colorPalette: 'Primary colors: bright blue (#3b82f6), sunny yellow (#fbbf24), cherry red (#ef4444), grass green (#22c55e). White background.',
    typography: 'Rounded bold sans-serif (Baloo 2 or Fredoka). Large, chunky, friendly.',
    layoutStyle: 'Rounded everything, bouncy elements, cartoon-style illustrations, big touch targets.',
    density: 'sparse',
    mood: 'Fun, energetic, safe. Kids educational app or toy store.',
    cssApproach: 'Tailwind with large border-radius, big fonts, and GSAP bounce animations.',
  },
  {
    name: 'dark-hacker',
    colorPalette: 'Pure black (#000) with phosphor green (#00ff41) and amber (#ffb000). Terminal aesthetic.',
    typography: 'Monospace only (JetBrains Mono or Fira Code). Fixed-width everything.',
    layoutStyle: 'Terminal-style panels, ASCII art, command-line interfaces, blinking cursors.',
    density: 'dense',
    mood: 'Technical, secretive, underground. Like a hacking toolkit or CLI dashboard.',
    cssApproach: 'Custom CSS for terminal effects, blinking animations, scanlines.',
  },
  {
    name: 'newspaper-classic',
    colorPalette: 'Off-white (#faf8f5), near-black (#1a1a1a), muted red (#8b2500) for accents. Sepia tones.',
    typography: 'Serif headlines (Merriweather or Lora), serif body text. Column-based reading.',
    layoutStyle: 'Multi-column text layout, horizontal rules, pull quotes, drop caps.',
    density: 'dense',
    mood: 'Authoritative, traditional, literary. Broadsheet newspaper or literary journal.',
    cssApproach: 'CSS columns, custom drop-cap styling, thin borders and rules.',
  },
  {
    name: 'minimal-zen',
    colorPalette: 'Near-white (#fafafa), stone gray (#a8a29e), charcoal (#292524). One muted accent: sage or dusty rose.',
    typography: 'Thin-weight sans-serif (Outfit or Libre Franklin light). Maximum whitespace.',
    layoutStyle: 'Extreme whitespace, single-column, huge margins, one element at a time.',
    density: 'sparse',
    mood: 'Calm, meditative, intentional. Japanese-inspired minimalism.',
    cssApproach: 'Tailwind with custom wide spacing. Almost no borders or shadows.',
  },
  {
    name: 'retro-90s',
    colorPalette: 'Teal (#008080), magenta (#ff00ff), lime (#00ff00), silver (#c0c0c0). Gray backgrounds.',
    typography: 'System fonts (Arial, Comic Sans, Times New Roman). Pixelated accents.',
    layoutStyle: 'Table-like layouts, beveled buttons, visible borders, hit counters, under-construction banners.',
    density: 'dense',
    mood: 'Nostalgic, playful, deliberately dated. GeoCities and early web.',
    cssApproach: 'Inline-style heavy, table layouts, beveled borders, background tiles.',
  },
  {
    name: 'luxury-dark',
    colorPalette: 'Deep charcoal (#1a1a1a), gold (#c9a84c), off-white (#e8e4dc). No bright colors.',
    typography: 'Elegant serif (Cormorant Garamond) for headlines, light sans-serif for body. Generous letter-spacing.',
    layoutStyle: 'Full-bleed images, thin gold borders, large hero sections, cinematic feel.',
    density: 'sparse',
    mood: 'Premium, exclusive, refined. High-end fashion or luxury hotel.',
    cssApproach: 'Custom CSS for gold accents and typography. Tailwind for layout.',
  },
  {
    name: 'retro-synthwave',
    colorPalette: 'Dark navy (#0f0728), hot pink (#ff2d95), electric blue (#00b4d8), chrome (#e0e0e0). Sunset gradients.',
    typography: 'Retro display font (Audiowide or Press Start 2P for accents). Clean sans for body.',
    layoutStyle: 'Grid lines receding to horizon, chrome/metallic effects, sunset gradient backgrounds.',
    density: 'balanced',
    mood: '80s retrofuturism, Miami Vice aesthetic. Outrun and vaporwave culture.',
    cssApproach: 'CSS gradients, custom grid-line backgrounds, glow text-shadows.',
  },
  {
    name: 'nature-botanical',
    colorPalette: 'Forest green (#2d5016), cream (#fffbeb), brown (#78350f), moss (#6b7e3f). Natural palette.',
    typography: 'Organic serif (Libre Baskerville) with clean sans-serif (Karla) for UI. Refined but natural.',
    layoutStyle: 'Leaf/vine decorative elements, soft photo backgrounds, rounded organic shapes.',
    density: 'balanced',
    mood: 'Earthy, sustainable, natural. Botanical garden or eco-brand.',
    cssApproach: 'Tailwind with green/brown palette. Decorative SVG elements.',
  },
  {
    name: 'glassmorphism-modern',
    colorPalette: 'Soft gradients behind frosted glass: lavender, peach, sky blue. White text on blur.',
    typography: 'Modern geometric sans-serif (Poppins or Plus Jakarta Sans). Medium weight, clean.',
    layoutStyle: 'Frosted glass cards (backdrop-blur), layered translucent panels, floating elements.',
    density: 'balanced',
    mood: 'Modern, airy, iOS-inspired. Tech startup or design portfolio.',
    cssApproach: 'Tailwind backdrop-blur, bg-white/10 patterns, subtle shadows.',
  },
  {
    name: 'industrial-tech',
    colorPalette: 'Gunmetal (#2b2d2f), safety orange (#ff6b00), concrete gray (#9ca3af), steel (#374151).',
    typography: 'Condensed sans-serif (Barlow Condensed or Oswald). Uppercase headers, tight tracking.',
    layoutStyle: 'Angular shapes, diagonal stripes, heavy borders, badge/tag UI elements.',
    density: 'dense',
    mood: 'Rugged, mechanical, no-nonsense. Construction firm or hardware manufacturer.',
    cssApproach: 'Tailwind with custom angle clips. Uppercase transform, tight letter-spacing.',
  },
  {
    name: 'pastel-soft',
    colorPalette: 'Baby pink (#fce4ec), lavender (#e8eaf6), mint (#e0f2f1), peach (#fff3e0), sky (#e3f2fd).',
    typography: 'Rounded sans-serif (Comfortaa or Varela Round). Soft, approachable, medium weight.',
    layoutStyle: 'Rounded cards, soft shadows, gentle gradients, pill-shaped buttons.',
    density: 'balanced',
    mood: 'Gentle, approachable, friendly. Wellness app or baby products.',
    cssApproach: 'Tailwind with pastel color overrides. Large border-radius values.',
  },
  {
    name: 'data-dashboard',
    colorPalette: 'Dark slate (#0f172a), chart blue (#3b82f6), chart green (#10b981), chart amber (#f59e0b), chart red (#ef4444).',
    typography: 'Technical sans-serif (IBM Plex Sans or Inter). Tabular numbers for data.',
    layoutStyle: 'Dense grid of cards with charts, KPI tiles, sidebar navigation, data tables.',
    density: 'dense',
    mood: 'Analytical, data-driven, professional. Analytics platform or monitoring tool.',
    cssApproach: 'Tailwind grid system with Chart.js integration. Dark background panels.',
  },
  {
    name: 'magazine-editorial',
    colorPalette: 'White, black, and one bold accent per section (coral, teal, or mustard). High contrast imagery.',
    typography: 'Strong serif for headlines (Playfair Display), clean sans for body (Source Sans 3). Dramatic size contrast.',
    layoutStyle: 'Magazine grid with varying card sizes, full-bleed hero images, text overlays.',
    density: 'balanced',
    mood: 'Stylish, curated, visually-driven. Fashion magazine or design publication.',
    cssApproach: 'CSS grid with span variations. Object-fit images, text overlays.',
  },
  {
    name: 'sci-fi-interface',
    colorPalette: 'Deep space (#050510), hologram blue (#00a8ff), grid cyan (#0ff), warning amber (#ff9f00).',
    typography: 'Futuristic sans (Exo 2 or Rajdhani). Uppercase labels, wide letter-spacing.',
    layoutStyle: 'HUD-style overlays, hexagonal elements, radar circles, animated grid backgrounds.',
    density: 'dense',
    mood: 'Futuristic command center. Spaceship bridge or military tech.',
    cssApproach: 'Heavy custom CSS for HUD elements, SVG overlays, CSS animations.',
  },
  {
    name: 'vintage-letterpress',
    colorPalette: 'Aged paper (#f4ead5), ink brown (#3e2723), dusty red (#a0522d), faded blue (#607d8b).',
    typography: 'Decorative serif (Abril Fatface for display, Crimson Text for body). Letterpress texture feel.',
    layoutStyle: 'Centered layouts, ornamental dividers, badge/stamp design elements, border frames.',
    density: 'balanced',
    mood: 'Nostalgic, handcrafted, authentic. Craft brewery or artisan workshop.',
    cssApproach: 'Custom CSS for texture overlays and ornamental borders.',
  },
  {
    name: 'gaming-esports',
    colorPalette: 'Jet black (#0a0a0a), electric red (#ff1744), neon yellow (#eeff41), dark gray (#1a1a2e).',
    typography: 'Angular display font (Teko or Russo One). Bold, aggressive, all-caps.',
    layoutStyle: 'Angled clip-paths, intense gradients, card hover effects with scale, leaderboard tables.',
    density: 'dense',
    mood: 'Intense, competitive, high-energy. Esports team or gaming tournament.',
    cssApproach: 'Tailwind with clip-path custom CSS. Aggressive hover transitions.',
  },
  {
    name: 'scandinavian-clean',
    colorPalette: 'White (#ffffff), light wood (#deb887), charcoal (#333333), muted blue (#6b8fa3).',
    typography: 'Clean geometric sans-serif (Outfit or DM Sans). Consistent medium weight, clear hierarchy.',
    layoutStyle: 'Plenty of whitespace, simple grid, no decoration, functional and honest.',
    density: 'sparse',
    mood: 'Simple, functional, honest. IKEA-inspired or Nordic design studio.',
    cssApproach: 'Tailwind with minimal custom CSS. Maximum simplicity.',
  },
  {
    name: 'comic-pop-art',
    colorPalette: 'Bold primaries: red (#ef4444), blue (#2563eb), yellow (#fbbf24). Black outlines, white dots.',
    typography: 'Comic-style (Bangers or Permanent Marker). Bold, expressive, varied sizes.',
    layoutStyle: 'Panel grid like comic strips, speech bubbles, halftone dot patterns, thick black outlines.',
    density: 'balanced',
    mood: 'Energetic, fun, expressive. Comic book store or pop culture blog.',
    cssApproach: 'Custom CSS for halftone patterns, thick borders, speech bubble shapes.',
  },
  {
    name: 'government-official',
    colorPalette: 'Navy (#1b3a60), white, light blue (#e8f0fe), dark gray (#374151). Seal gold (#b8860b).',
    typography: 'Traditional sans-serif (Source Sans 3 or Roboto). Clear, accessible, formal.',
    layoutStyle: 'Structured header with seal/logo, sidebar navigation, form-heavy content, tables.',
    density: 'dense',
    mood: 'Official, trustworthy, accessible. Government portal or institutional site.',
    cssApproach: 'Tailwind with accessibility-first approach. Clear form styling.',
  },
  {
    name: 'art-deco-gatsby',
    colorPalette: 'Black (#0a0a0a), gold (#d4af37), cream (#faf3e0), emerald (#065f46). Metallic accents.',
    typography: 'Art deco display font (Poiret One or Tenor Sans). Geometric, elegant.',
    layoutStyle: 'Geometric patterns, fan/sunburst motifs, symmetrical layouts, gold line borders.',
    density: 'balanced',
    mood: 'Glamorous, theatrical, 1920s luxury. Cocktail bar or jazz venue.',
    cssApproach: 'Custom CSS for geometric patterns and gold gradient borders.',
  },
];

export const BRAND_PATTERNS: BrandProfile[] = [
  { domain: 'google.com', styleDirective: 'Clean Material Design. White background, blue (#4285F4) / red (#EA4335) / yellow (#FBBC05) / green (#34A853) accents. Product Sans-like typography. Card-based UI with subtle shadows. Simple, functional, lots of whitespace.' },
  { domain: 'github.com', styleDirective: 'Dark sidebar (#0d1117), light content area. Segmented controls, pill tabs. Monospace for code. Octicon-style icons. Repository-centric layout with contribution graphs. Muted blue-gray color scheme.' },
  { domain: 'reddit.com', styleDirective: 'White/light gray cards, upvote/downvote arrows, orangered (#ff4500) accent. Dense feed of posts with karma scores. Subreddit sidebar, flair badges. Community-driven feel.' },
  { domain: 'amazon.com', styleDirective: 'White background, dark navy header (#131921), orange (#ff9900) accent for buttons/CTAs. Dense product grid with star ratings, pricing, Prime badges. Left sidebar filters.' },
  { domain: 'twitter.com', styleDirective: 'Clean white/dark feed layout. Blue (#1d9bf0) accent. Tweet cards with avatar, handle, timestamp. Like/retweet/reply actions. Trending sidebar. Character-count feel.' },
  { domain: 'x.com', styleDirective: 'Clean white/dark feed layout. Blue (#1d9bf0) accent. Tweet cards with avatar, handle, timestamp. Like/retweet/reply actions. Trending sidebar. Minimalist rebrand.' },
  { domain: 'youtube.com', styleDirective: 'White/dark background, red (#ff0000) accent. Video thumbnail grid with duration badges. Channel avatars, view counts. Left sidebar with subscriptions. Video player with controls.' },
  { domain: 'wikipedia.org', styleDirective: 'Stark white background, blue links (#0645ad), minimal styling. Dense text-heavy layout with table of contents sidebar. Sans-serif body text. Encyclopedia formatting with references.' },
  { domain: 'nytimes.com', styleDirective: 'Classic newspaper: white background, black serif headlines (Cheltenham-style), gray body text. Multi-column article layout, section headers, bylines with timestamps.' },
  { domain: 'spotify.com', styleDirective: 'Dark background (#121212), bright green (#1db954) accent. Album art grid, playlist sidebar, bottom player bar. Circular artist images. Music-centric navigation.' },
  { domain: 'netflix.com', styleDirective: 'Black background, red (#e50914) accent. Horizontal carousels of title cards with hover-expand. Hero billboard, category rows. Cinematic, dark, immersive.' },
  { domain: 'apple.com', styleDirective: 'Ultra-clean white, SF Pro-style typography. Massive hero images, minimal text, premium product photography. Smooth scroll animations, full-width sections. Understated elegance.' },
  { domain: 'twitch.tv', styleDirective: 'Dark theme (#0e0e10), purple (#9146ff) accent. Video player with chat sidebar. Stream tiles with viewer counts, live badges. Category/game navigation. Community-driven.' },
  { domain: 'linkedin.com', styleDirective: 'White background, blue (#0a66c2) accent. Professional feed with connection cards, job listings, company pages. Resume-style profiles, endorsement badges.' },
  { domain: 'stackoverflow.com', styleDirective: 'White background, orange (#f48024) accent. Question/answer format with vote counts, accepted answer checkmarks, tags, code blocks with syntax highlighting.' },
  { domain: 'medium.com', styleDirective: 'Clean white, elegant serif typography (Charter or Georgia). Centered article layout, clap button, author cards, reading time estimates. Literary, long-form feel.' },
  { domain: 'pinterest.com', styleDirective: 'Masonry grid of image pins. Red (#e60023) accent. Rounded corners, save buttons, board organization. Visual discovery layout.' },
  { domain: 'discord.com', styleDirective: 'Dark theme (#36393f), blurple (#5865f2) accent. Server sidebar, channel list, message feed with avatars. Emoji reactions, voice channel indicators.' },
  { domain: 'instagram.com', styleDirective: 'White background, gradient accent (pink-orange-purple). Square photo grid, stories bar at top, like/comment actions. Clean and visual-first.' },
  { domain: 'ebay.com', styleDirective: 'White background, blue/red/yellow/green brand colors. Auction listings with bid counts, "Buy It Now" buttons, seller ratings. Category mega-menu.' },
  { domain: 'craigslist.org', styleDirective: 'Extremely minimal: plain HTML, blue links, no styling, no images. Dense categorized list layout. Text-only, utilitarian, deliberately unstyled.' },
  { domain: 'hacker-news.com', styleDirective: 'Orange (#ff6600) header bar, beige (#f6f6ef) background. Dense list of links with point scores, comment counts. Minimal, text-heavy, no images.' },
  { domain: 'ycombinator.com', styleDirective: 'Orange (#ff6600) header bar, beige (#f6f6ef) background. Dense list of links with point scores. HN-style minimal text interface.' },
  { domain: 'bbc.com', styleDirective: 'White background, BBC red (#bb1919), strong black headlines. Grid of news stories with thumbnails. Section navigation, authoritative journalism layout.' },
  { domain: 'cnn.com', styleDirective: 'Red (#cc0000) accent, white/dark background. Breaking news banner, video-heavy hero, dense story grid. 24-hour news feel.' },
];

export const KEYWORD_STYLE_MAPPINGS: KeywordMapping[] = [
  { keyword: 'retro', moodName: 'retro-90s' },
  { keyword: '90s', moodName: 'retro-90s' },
  { keyword: 'vintage', moodName: 'vintage-letterpress' },
  { keyword: 'terminal', moodName: 'dark-hacker' },
  { keyword: 'hacker', moodName: 'dark-hacker' },
  { keyword: 'cyber', moodName: 'neon-cyberpunk' },
  { keyword: 'neon', moodName: 'neon-cyberpunk' },
  { keyword: 'punk', moodName: 'neon-cyberpunk' },
  { keyword: 'government', moodName: 'government-official' },
  { keyword: '.gov', moodName: 'government-official' },
  { keyword: 'kids', moodName: 'playful-children' },
  { keyword: 'children', moodName: 'playful-children' },
  { keyword: 'edu', moodName: 'playful-children' },
  { keyword: 'news', moodName: 'newspaper-classic' },
  { keyword: 'journal', moodName: 'newspaper-classic' },
  { keyword: 'times', moodName: 'newspaper-classic' },
  { keyword: 'gazette', moodName: 'newspaper-classic' },
  { keyword: 'zen', moodName: 'minimal-zen' },
  { keyword: 'calm', moodName: 'minimal-zen' },
  { keyword: 'meditation', moodName: 'minimal-zen' },
  { keyword: 'wellness', moodName: 'minimal-zen' },
  { keyword: 'luxury', moodName: 'luxury-dark' },
  { keyword: 'premium', moodName: 'luxury-dark' },
  { keyword: 'fashion', moodName: 'luxury-dark' },
  { keyword: 'boutique', moodName: 'luxury-dark' },
  { keyword: 'synthwave', moodName: 'retro-synthwave' },
  { keyword: 'vaporwave', moodName: 'retro-synthwave' },
  { keyword: 'outrun', moodName: 'retro-synthwave' },
  { keyword: 'radio', moodName: 'retro-synthwave' },
  { keyword: 'dashboard', moodName: 'data-dashboard' },
  { keyword: 'analytics', moodName: 'data-dashboard' },
  { keyword: 'monitor', moodName: 'data-dashboard' },
  { keyword: 'metrics', moodName: 'data-dashboard' },
  { keyword: 'finance', moodName: 'data-dashboard' },
  { keyword: 'stock', moodName: 'data-dashboard' },
  { keyword: 'game', moodName: 'gaming-esports' },
  { keyword: 'esport', moodName: 'gaming-esports' },
  { keyword: 'arena', moodName: 'gaming-esports' },
  { keyword: 'play', moodName: 'gaming-esports' },
  { keyword: 'garden', moodName: 'nature-botanical' },
  { keyword: 'botanical', moodName: 'nature-botanical' },
  { keyword: 'plant', moodName: 'nature-botanical' },
  { keyword: 'eco', moodName: 'nature-botanical' },
  { keyword: 'organic', moodName: 'warm-organic' },
  { keyword: 'bakery', moodName: 'warm-organic' },
  { keyword: 'cafe', moodName: 'warm-organic' },
  { keyword: 'kitchen', moodName: 'warm-organic' },
  { keyword: 'recipe', moodName: 'warm-organic' },
  { keyword: 'comic', moodName: 'comic-pop-art' },
  { keyword: 'manga', moodName: 'comic-pop-art' },
  { keyword: 'art', moodName: 'magazine-editorial' },
  { keyword: 'gallery', moodName: 'magazine-editorial' },
  { keyword: 'magazine', moodName: 'magazine-editorial' },
  { keyword: 'corporate', moodName: 'clean-corporate' },
  { keyword: 'enterprise', moodName: 'clean-corporate' },
  { keyword: 'saas', moodName: 'clean-corporate' },
  { keyword: 'consulting', moodName: 'clean-corporate' },
  { keyword: 'space', moodName: 'sci-fi-interface' },
  { keyword: 'mars', moodName: 'sci-fi-interface' },
  { keyword: 'colony', moodName: 'sci-fi-interface' },
  { keyword: 'starship', moodName: 'sci-fi-interface' },
  { keyword: 'sci-fi', moodName: 'sci-fi-interface' },
  { keyword: 'deco', moodName: 'art-deco-gatsby' },
  { keyword: 'gatsby', moodName: 'art-deco-gatsby' },
  { keyword: 'jazz', moodName: 'art-deco-gatsby' },
  { keyword: 'cocktail', moodName: 'art-deco-gatsby' },
  { keyword: 'baby', moodName: 'pastel-soft' },
  { keyword: 'gentle', moodName: 'pastel-soft' },
  { keyword: 'soft', moodName: 'pastel-soft' },
  { keyword: 'nordic', moodName: 'scandinavian-clean' },
  { keyword: 'minimal', moodName: 'scandinavian-clean' },
  { keyword: 'simple', moodName: 'scandinavian-clean' },
  { keyword: 'industrial', moodName: 'industrial-tech' },
  { keyword: 'construction', moodName: 'industrial-tech' },
  { keyword: 'hardware', moodName: 'industrial-tech' },
  { keyword: 'tool', moodName: 'industrial-tech' },
  { keyword: 'glass', moodName: 'glassmorphism-modern' },
  { keyword: 'modern', moodName: 'glassmorphism-modern' },
  { keyword: 'startup', moodName: 'glassmorphism-modern' },
  { keyword: 'app', moodName: 'glassmorphism-modern' },
  { keyword: 'brutalist', moodName: 'brutalist-editorial' },
  { keyword: 'raw', moodName: 'brutalist-editorial' },
  { keyword: 'zine', moodName: 'brutalist-editorial' },
  { keyword: 'horror', moodName: 'neon-cyberpunk' },
  { keyword: 'haunted', moodName: 'neon-cyberpunk' },
  { keyword: 'ocean', moodName: 'nature-botanical' },
  { keyword: 'pet', moodName: 'pastel-soft' },
  { keyword: 'adopt', moodName: 'pastel-soft' },
  { keyword: 'library', moodName: 'newspaper-classic' },
  { keyword: 'archive', moodName: 'newspaper-classic' },
  { keyword: 'weather', moodName: 'glassmorphism-modern' },
  { keyword: 'city', moodName: 'clean-corporate' },
  { keyword: 'planner', moodName: 'clean-corporate' },
];
